# File: nixpacks.toml
# Konfigurasi ini memberitahu Railway/Nixpacks untuk menginstal Google Chrome

[phases.setup]
# 1. Instal paket dasar yang dibutuhkan untuk menambah repo Chrome
aptPackages = ["wget", "gnupg"]

# 2. Jalankan perintah yang sama seperti di VPS untuk menambah repo dan menginstal Chrome
cmds = [
    "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -",
    "sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google-chrome.list'",
    "apt-get update",
    "apt-get install -y google-chrome-stable"
]
